// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

#pragma once
#ifndef WINRT_Windows_System_Power_Thermal_1_H
#define WINRT_Windows_System_Power_Thermal_1_H
#include "winrt/impl/Windows.System.Power.Thermal.0.h"
WINRT_EXPORT namespace winrt::Windows::System::Power::Thermal
{
    struct __declspec(empty_bases) IPowerThermalChannelConfiguration :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IPowerThermalChannelConfiguration>
    {
        IPowerThermalChannelConfiguration(std::nullptr_t = nullptr) noexcept {}
        IPowerThermalChannelConfiguration(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IPowerThermalChannelDataConsumer :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IPowerThermalChannelDataConsumer>
    {
        IPowerThermalChannelDataConsumer(std::nullptr_t = nullptr) noexcept {}
        IPowerThermalChannelDataConsumer(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IPowerThermalChannelDataConsumerFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IPowerThermalChannelDataConsumerFactory>
    {
        IPowerThermalChannelDataConsumerFactory(std::nullptr_t = nullptr) noexcept {}
        IPowerThermalChannelDataConsumerFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IPowerThermalChannelDataProducer :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IPowerThermalChannelDataProducer>
    {
        IPowerThermalChannelDataProducer(std::nullptr_t = nullptr) noexcept {}
        IPowerThermalChannelDataProducer(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IPowerThermalChannelDataProducerFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IPowerThermalChannelDataProducerFactory>
    {
        IPowerThermalChannelDataProducerFactory(std::nullptr_t = nullptr) noexcept {}
        IPowerThermalChannelDataProducerFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IPowerThermalChannelDataReceivedEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IPowerThermalChannelDataReceivedEventArgs>
    {
        IPowerThermalChannelDataReceivedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IPowerThermalChannelDataReceivedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IPowerThermalChannelDiagnostics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IPowerThermalChannelDiagnostics>
    {
        IPowerThermalChannelDiagnostics(std::nullptr_t = nullptr) noexcept {}
        IPowerThermalChannelDiagnostics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IPowerThermalChannelDiagnosticsStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IPowerThermalChannelDiagnosticsStatics>
    {
        IPowerThermalChannelDiagnosticsStatics(std::nullptr_t = nullptr) noexcept {}
        IPowerThermalChannelDiagnosticsStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IPowerThermalChannelFinderStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IPowerThermalChannelFinderStatics>
    {
        IPowerThermalChannelFinderStatics(std::nullptr_t = nullptr) noexcept {}
        IPowerThermalChannelFinderStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
