// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

#pragma once
#ifndef WINRT_Windows_UI_Shell_CompanionWindows_1_H
#define WINRT_Windows_UI_Shell_CompanionWindows_1_H
#include "winrt/impl/Windows.UI.Shell.CompanionWindows.0.h"
WINRT_EXPORT namespace winrt::Windows::UI::Shell::CompanionWindows
{
    struct __declspec(empty_bases) ICompanionWindowCoordinator :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICompanionWindowCoordinator>
    {
        ICompanionWindowCoordinator(std::nullptr_t = nullptr) noexcept {}
        ICompanionWindowCoordinator(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICompanionWindowCoordinatorStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICompanionWindowCoordinatorStatics>
    {
        ICompanionWindowCoordinatorStatics(std::nullptr_t = nullptr) noexcept {}
        ICompanionWindowCoordinatorStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICompanionWindowRequest :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICompanionWindowRequest>
    {
        ICompanionWindowRequest(std::nullptr_t = nullptr) noexcept {}
        ICompanionWindowRequest(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICompanionWindowRequestResult :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICompanionWindowRequestResult>
    {
        ICompanionWindowRequestResult(std::nullptr_t = nullptr) noexcept {}
        ICompanionWindowRequestResult(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICompanionWindowRequestStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICompanionWindowRequestStatics>
    {
        ICompanionWindowRequestStatics(std::nullptr_t = nullptr) noexcept {}
        ICompanionWindowRequestStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
