// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

#pragma once
#ifndef WINRT_Windows_Management_Update_1_H
#define WINRT_Windows_Management_Update_1_H
#include "winrt/impl/Windows.Management.Update.0.h"
WINRT_EXPORT namespace winrt::Windows::Management::Update
{
    struct __declspec(empty_bases) IPreviewBuildsManager :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IPreviewBuildsManager>
    {
        IPreviewBuildsManager(std::nullptr_t = nullptr) noexcept {}
        IPreviewBuildsManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IPreviewBuildsManagerStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IPreviewBuildsManagerStatics>
    {
        IPreviewBuildsManagerStatics(std::nullptr_t = nullptr) noexcept {}
        IPreviewBuildsManagerStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IPreviewBuildsState :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IPreviewBuildsState>
    {
        IPreviewBuildsState(std::nullptr_t = nullptr) noexcept {}
        IPreviewBuildsState(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsSoftwareUpdate :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsSoftwareUpdate>
    {
        IWindowsSoftwareUpdate(std::nullptr_t = nullptr) noexcept {}
        IWindowsSoftwareUpdate(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsSoftwareUpdateActionInfo :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsSoftwareUpdateActionInfo>
    {
        IWindowsSoftwareUpdateActionInfo(std::nullptr_t = nullptr) noexcept {}
        IWindowsSoftwareUpdateActionInfo(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsSoftwareUpdateActionInfoFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsSoftwareUpdateActionInfoFactory>
    {
        IWindowsSoftwareUpdateActionInfoFactory(std::nullptr_t = nullptr) noexcept {}
        IWindowsSoftwareUpdateActionInfoFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsSoftwareUpdateActionProgress :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsSoftwareUpdateActionProgress>
    {
        IWindowsSoftwareUpdateActionProgress(std::nullptr_t = nullptr) noexcept {}
        IWindowsSoftwareUpdateActionProgress(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsSoftwareUpdateActionResultInfo :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsSoftwareUpdateActionResultInfo>
    {
        IWindowsSoftwareUpdateActionResultInfo(std::nullptr_t = nullptr) noexcept {}
        IWindowsSoftwareUpdateActionResultInfo(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsSoftwareUpdateAppPackageInfo :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsSoftwareUpdateAppPackageInfo>
    {
        IWindowsSoftwareUpdateAppPackageInfo(std::nullptr_t = nullptr) noexcept {}
        IWindowsSoftwareUpdateAppPackageInfo(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsSoftwareUpdateAppPackageInfoFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsSoftwareUpdateAppPackageInfoFactory>
    {
        IWindowsSoftwareUpdateAppPackageInfoFactory(std::nullptr_t = nullptr) noexcept {}
        IWindowsSoftwareUpdateAppPackageInfoFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsSoftwareUpdateApprovalInfo :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsSoftwareUpdateApprovalInfo>
    {
        IWindowsSoftwareUpdateApprovalInfo(std::nullptr_t = nullptr) noexcept {}
        IWindowsSoftwareUpdateApprovalInfo(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsSoftwareUpdateApprovalInfoFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsSoftwareUpdateApprovalInfoFactory>
    {
        IWindowsSoftwareUpdateApprovalInfoFactory(std::nullptr_t = nullptr) noexcept {}
        IWindowsSoftwareUpdateApprovalInfoFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsSoftwareUpdateExecutionInfo :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsSoftwareUpdateExecutionInfo>
    {
        IWindowsSoftwareUpdateExecutionInfo(std::nullptr_t = nullptr) noexcept {}
        IWindowsSoftwareUpdateExecutionInfo(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsSoftwareUpdateExecutionInfoFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsSoftwareUpdateExecutionInfoFactory>
    {
        IWindowsSoftwareUpdateExecutionInfoFactory(std::nullptr_t = nullptr) noexcept {}
        IWindowsSoftwareUpdateExecutionInfoFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsSoftwareUpdateFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsSoftwareUpdateFactory>
    {
        IWindowsSoftwareUpdateFactory(std::nullptr_t = nullptr) noexcept {}
        IWindowsSoftwareUpdateFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsSoftwareUpdateLocalizationInfo :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsSoftwareUpdateLocalizationInfo>
    {
        IWindowsSoftwareUpdateLocalizationInfo(std::nullptr_t = nullptr) noexcept {}
        IWindowsSoftwareUpdateLocalizationInfo(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsSoftwareUpdateLocalizationInfoFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsSoftwareUpdateLocalizationInfoFactory>
    {
        IWindowsSoftwareUpdateLocalizationInfoFactory(std::nullptr_t = nullptr) noexcept {}
        IWindowsSoftwareUpdateLocalizationInfoFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsSoftwareUpdateOptionalActionInfo :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsSoftwareUpdateOptionalActionInfo>
    {
        IWindowsSoftwareUpdateOptionalActionInfo(std::nullptr_t = nullptr) noexcept {}
        IWindowsSoftwareUpdateOptionalActionInfo(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsSoftwareUpdateOptionalActionInfoFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsSoftwareUpdateOptionalActionInfoFactory>
    {
        IWindowsSoftwareUpdateOptionalActionInfoFactory(std::nullptr_t = nullptr) noexcept {}
        IWindowsSoftwareUpdateOptionalActionInfoFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsSoftwareUpdateOptionalInfo :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsSoftwareUpdateOptionalInfo>
    {
        IWindowsSoftwareUpdateOptionalInfo(std::nullptr_t = nullptr) noexcept {}
        IWindowsSoftwareUpdateOptionalInfo(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsSoftwareUpdateOptionalInfoFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsSoftwareUpdateOptionalInfoFactory>
    {
        IWindowsSoftwareUpdateOptionalInfoFactory(std::nullptr_t = nullptr) noexcept {}
        IWindowsSoftwareUpdateOptionalInfoFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsSoftwareUpdateProvider :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsSoftwareUpdateProvider>
    {
        IWindowsSoftwareUpdateProvider(std::nullptr_t = nullptr) noexcept {}
        IWindowsSoftwareUpdateProvider(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsSoftwareUpdateProviderActionResult :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsSoftwareUpdateProviderActionResult>
    {
        IWindowsSoftwareUpdateProviderActionResult(std::nullptr_t = nullptr) noexcept {}
        IWindowsSoftwareUpdateProviderActionResult(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsSoftwareUpdateProviderActionResultFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsSoftwareUpdateProviderActionResultFactory>
    {
        IWindowsSoftwareUpdateProviderActionResultFactory(std::nullptr_t = nullptr) noexcept {}
        IWindowsSoftwareUpdateProviderActionResultFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsSoftwareUpdateProviderFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsSoftwareUpdateProviderFactory>
    {
        IWindowsSoftwareUpdateProviderFactory(std::nullptr_t = nullptr) noexcept {}
        IWindowsSoftwareUpdateProviderFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsSoftwareUpdateProviderPayloadFileInfo :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsSoftwareUpdateProviderPayloadFileInfo>
    {
        IWindowsSoftwareUpdateProviderPayloadFileInfo(std::nullptr_t = nullptr) noexcept {}
        IWindowsSoftwareUpdateProviderPayloadFileInfo(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsSoftwareUpdateProviderStatus :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsSoftwareUpdateProviderStatus>
    {
        IWindowsSoftwareUpdateProviderStatus(std::nullptr_t = nullptr) noexcept {}
        IWindowsSoftwareUpdateProviderStatus(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsSoftwareUpdateProviderStatusFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsSoftwareUpdateProviderStatusFactory>
    {
        IWindowsSoftwareUpdateProviderStatusFactory(std::nullptr_t = nullptr) noexcept {}
        IWindowsSoftwareUpdateProviderStatusFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsSoftwareUpdateResult :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsSoftwareUpdateResult>
    {
        IWindowsSoftwareUpdateResult(std::nullptr_t = nullptr) noexcept {}
        IWindowsSoftwareUpdateResult(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsSoftwareUpdateResultFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsSoftwareUpdateResultFactory>
    {
        IWindowsSoftwareUpdateResultFactory(std::nullptr_t = nullptr) noexcept {}
        IWindowsSoftwareUpdateResultFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsSoftwareUpdateScanResult :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsSoftwareUpdateScanResult>
    {
        IWindowsSoftwareUpdateScanResult(std::nullptr_t = nullptr) noexcept {}
        IWindowsSoftwareUpdateScanResult(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsSoftwareUpdateScanResultFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsSoftwareUpdateScanResultFactory>
    {
        IWindowsSoftwareUpdateScanResultFactory(std::nullptr_t = nullptr) noexcept {}
        IWindowsSoftwareUpdateScanResultFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsSoftwareUpdateVersion :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsSoftwareUpdateVersion>
    {
        IWindowsSoftwareUpdateVersion(std::nullptr_t = nullptr) noexcept {}
        IWindowsSoftwareUpdateVersion(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsSoftwareUpdateVersionFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsSoftwareUpdateVersionFactory>
    {
        IWindowsSoftwareUpdateVersionFactory(std::nullptr_t = nullptr) noexcept {}
        IWindowsSoftwareUpdateVersionFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsUpdate :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdate>
    {
        IWindowsUpdate(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdate(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsUpdateActionCompletedEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateActionCompletedEventArgs>
    {
        IWindowsUpdateActionCompletedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateActionCompletedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsUpdateActionProgress :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateActionProgress>
    {
        IWindowsUpdateActionProgress(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateActionProgress(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsUpdateActionResult :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateActionResult>
    {
        IWindowsUpdateActionResult(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateActionResult(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsUpdateAdministrator :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateAdministrator>
    {
        IWindowsUpdateAdministrator(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateAdministrator(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsUpdateAdministratorStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateAdministratorStatics>
    {
        IWindowsUpdateAdministratorStatics(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateAdministratorStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsUpdateApprovalData :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateApprovalData>
    {
        IWindowsUpdateApprovalData(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateApprovalData(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsUpdateAttentionRequiredInfo :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateAttentionRequiredInfo>
    {
        IWindowsUpdateAttentionRequiredInfo(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateAttentionRequiredInfo(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsUpdateAttentionRequiredReasonChangedEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateAttentionRequiredReasonChangedEventArgs>
    {
        IWindowsUpdateAttentionRequiredReasonChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateAttentionRequiredReasonChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsUpdateGetAdministratorResult :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateGetAdministratorResult>
    {
        IWindowsUpdateGetAdministratorResult(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateGetAdministratorResult(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsUpdateItem :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateItem>
    {
        IWindowsUpdateItem(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateItem(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsUpdateManager :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateManager>
    {
        IWindowsUpdateManager(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsUpdateManager2 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateManager2>
    {
        IWindowsUpdateManager2(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateManager2(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsUpdateManagerFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateManagerFactory>
    {
        IWindowsUpdateManagerFactory(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateManagerFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsUpdateManagerFactory2 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateManagerFactory2>
    {
        IWindowsUpdateManagerFactory2(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateManagerFactory2(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsUpdateManagerScanOptions :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateManagerScanOptions>
    {
        IWindowsUpdateManagerScanOptions(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateManagerScanOptions(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsUpdateManagerScanOptionsFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateManagerScanOptionsFactory>
    {
        IWindowsUpdateManagerScanOptionsFactory(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateManagerScanOptionsFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsUpdateProgressChangedEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateProgressChangedEventArgs>
    {
        IWindowsUpdateProgressChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateProgressChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsUpdateRestartRequestOptions :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateRestartRequestOptions>
    {
        IWindowsUpdateRestartRequestOptions(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateRestartRequestOptions(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsUpdateRestartRequestOptionsFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateRestartRequestOptionsFactory>
    {
        IWindowsUpdateRestartRequestOptionsFactory(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateRestartRequestOptionsFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IWindowsUpdateScanCompletedEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWindowsUpdateScanCompletedEventArgs>
    {
        IWindowsUpdateScanCompletedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IWindowsUpdateScanCompletedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
