// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

#pragma once
#ifndef WINRT_Windows_ApplicationModel_Preview_2_H
#define WINRT_Windows_ApplicationModel_Preview_2_H
#include "winrt/impl/Windows.ApplicationModel.Preview.1.h"
WINRT_EXPORT namespace winrt::Windows::ApplicationModel::Preview
{
    struct __declspec(empty_bases) StartupAppInfoPreview : winrt::Windows::ApplicationModel::Preview::IStartupAppInfoPreview
    {
        StartupAppInfoPreview(std::nullptr_t) noexcept {}
        StartupAppInfoPreview(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Preview::IStartupAppInfoPreview(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) StartupAppsManagerPreview : winrt::Windows::ApplicationModel::Preview::IStartupAppsManagerPreview
    {
        StartupAppsManagerPreview(std::nullptr_t) noexcept {}
        StartupAppsManagerPreview(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::ApplicationModel::Preview::IStartupAppsManagerPreview(ptr, take_ownership_from_abi) {}
        static auto GetDefault();
    };
}
#endif
