// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

#pragma once
#ifndef WINRT_Windows_AI_Agents_Mcp_1_H
#define WINRT_Windows_AI_Agents_Mcp_1_H
#include "winrt/impl/Windows.AI.Agents.Mcp.0.h"
WINRT_EXPORT namespace winrt::Windows::AI::Agents::Mcp
{
    struct __declspec(empty_bases) IMcpMessageFilterExperimental :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMcpMessageFilterExperimental>
    {
        IMcpMessageFilterExperimental(std::nullptr_t = nullptr) noexcept {}
        IMcpMessageFilterExperimental(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMcpMessageFilterResponse :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMcpMessageFilterResponse>
    {
        IMcpMessageFilterResponse(std::nullptr_t = nullptr) noexcept {}
        IMcpMessageFilterResponse(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMcpMessageFilterResponseExperimental :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMcpMessageFilterResponseExperimental>
    {
        IMcpMessageFilterResponseExperimental(std::nullptr_t = nullptr) noexcept {}
        IMcpMessageFilterResponseExperimental(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMcpMessageFilterResponseExperimental2 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMcpMessageFilterResponseExperimental2>
    {
        IMcpMessageFilterResponseExperimental2(std::nullptr_t = nullptr) noexcept {}
        IMcpMessageFilterResponseExperimental2(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
