// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

#pragma once
#ifndef WINRT_Windows_AI_Agents_Mcp_2_H
#define WINRT_Windows_AI_Agents_Mcp_2_H
#include "winrt/impl/Windows.AI.Agents.Mcp.1.h"
WINRT_EXPORT namespace winrt::Windows::AI::Agents::Mcp
{
    struct __declspec(empty_bases) McpMessageFilterResponse : winrt::Windows::AI::Agents::Mcp::IMcpMessageFilterResponse
    {
        McpMessageFilterResponse(std::nullptr_t) noexcept {}
        McpMessageFilterResponse(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::AI::Agents::Mcp::IMcpMessageFilterResponse(ptr, take_ownership_from_abi) {}
    };
}
#endif
